apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
  namespace: votingapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - image: cmendes/vote:latest
        imagePullPolicy: Always
        name: vote
