sudo: false

language: java

jdk:
  - openjdk11

install: ./scripts/install.sh

cache:
  directories:
  - $HOME/.m2


env:
  matrix:
    - ROOT_POM="pom.xml"

branches:
  only:
    - master
    - /^release.*$/