sudo: false

language: java

jdk:
  - openjdk11

install: mvn -B install -U -DskipTests=true -f $ROOT_POM

cache:
  directories:
  - $HOME/.m2


env:
  matrix:
    - ROOT_POM="pom.xml"

branches:
  only:
    - master
    - /^release.*$/