apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result:before
        name: result
        ports:
        - containerPort: 80
          name: result
      nodeSelector:
        kops.k8s.io/instancegroup: web
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: result
    port: 80
    targetPort: 80
  selector:
    app: result
