apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: probes
data:
  probes.yaml: |
    vars:
      _probes.commonPath: "/etc/kubow/targets/voting-app"
      
    probes:

      CustomMetricsProbe:
        alias: result.latency.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.CustomMetricProbe
          period: 5000
          args.length: 5
          args.0: votingapp
          args.1: result
          args.2: selector?app=result&namespace=votingapp
          args.3: caddy_http_request_duration_seconds_success_99p
          args.4: latency

      DeploymentPropertiesProbe:
        alias: deployments.default.result.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.DeploymentInfoProbe
          period: 5000
          args.length: 2
          args.0: "votingapp"
          args.1: "result"
