apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: strategies
data:
  strategies.s: |
    module kuberainbow.strategies;
    import model "VotingAppSystem:Acme" { VotingAppSystem as M, KubernetesFam as K };
    import lib "tactics.s";
    import op "org.sa.rainbow.model.stitch.*";

    define boolean cHiRespTime = M.resultS.latency > M.MAX_RESPTIME;
    define boolean canAddPods = M.resultD.maxReplicas > M.resultD.desiredReplicas;
    define boolean canRemovePods = M.resultD.minReplicas < M.resultD.desiredReplicas;

    strategy ReduceRespTime [ cHiRespTime ] {
      t0: (cHiRespTime && canAddPods) -> addReplicas(1) @[30000 /*ms*/] {
        t0a: (success) -> done;
      }

      t2: (default) -> TNULL;
    }

    strategy ReduceCost [ !cHiRespTime ] {
      t0: (!cHiRespTime && canRemovePods) -> removeReplicas(1) @[30000 /*ms*/] {
        t0a: (success) -> done;
      }

      t1: (default) -> TNULL;
    }
