apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gauges
data:
  gauges.yaml: |
    gauge-types:
      KubeRainbowGaugeT:
        commands:
          setServiceProperty: Service.setServiceProperty (Object)
          setDeploymentInfo: Deployment.setDeploymentInfo (Object)
          setDeploymentProperty: Deployment.setDeploymentProperty (Object)
          setContainers: Deployment.setContainers (Object)
        setupParams:
          targetIP:
            type: String
            default: "127.0.0.1"
          propertyPath:
            type: String
            default: ""
          propertyName:
            type: String
            default: ""
          beaconPeriod:
            type: long
            default: 3000
          javaClass:
            type: String
            default: "org.sa.rainbow.translator.gauges.KubeGauge"
        configParams:
          targetProbeType:
            type: String
            default: ~
        comment: ""

    gauge-instances:
      EERTG1:
        type: KubeRainbowGaugeT
        model: "ZNewsSys:Acme"
        commands:
          "setServiceProperty()": "znn-service.setServiceProperty($<jsonValue>,<latency>)"
        setupValues:
          targetIP: "127.0.0.1"
        configValues:
          targetProbeType: znn-latency-probe@*
        comment: ""

      EERTG2:
        type: KubeRainbowGaugeT
        model: "ZNewsSys:Acme"
        commands:
          "setServiceProperty()": "znn-service.setServiceProperty($<jsonValue>,<latency>)"
        setupValues:
          targetIP: "127.0.0.1"
        configValues:
          targetProbeType: default-znn-latency@*
        comment: ""

      DIG1:
        type: KubeRainbowGaugeT
        model: "ZNewsSys:Acme"
        commands:
          "setDeploymentInfo()": znn.setDeploymentInfo($<jsonValue>)
        setupValues:
          targetIP: "127.0.0.1"
        configValues:
          targetProbeType: deployments.default.znn.probe@*
        comment: ""

    #  DIG2:
    #    type: KubeRainbowGaugeT
    #    model: "ZNewsSys:Acme"
    #    commands:
    #      "setDeploymentProperty()": "znn.setDeploymentProperty($<jsonValue>,<fidelity>)"
    #    setupValues:
    #      targetIP: "127.0.0.1"
    #      propertyName: "fidelity"
    #      propertyPath: "/containers/znn"
    #    configValues:
    #      targetProbeType: deployments.default.znn.probe@*
    #    comment: ""

      DIG3:
        type: KubeRainbowGaugeT
        model: "ZNewsSys:Acme"
        commands:
          "setContainers()": znn.setContainers($<jsonValue>)
        setupValues:
          targetIP: "127.0.0.1"
        configValues:
          targetProbeType: deployments.default.znn.probe@*
        comment: ""
