apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-slave
  name: locust-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-slave
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      containers:
      - name: locust
        image: cmendes/locust
        imagePullPolicy: Always
        env:
        - name: LOCUST_MODE
          value: "slave"
        - name: ATTACKED_HOST
          value: "kube-znn"
        - name: LOCUST_MASTER
          value: "locust-master"
        - name: LOCUST_FILE
          value: "/locustfile.py"
        - name: LOCUST_MASTER_BIND_PORT
          value: "5557"
        volumeMounts:
        - name: locustfile
          mountPath: /locustfile.py
          subPath: locustfile.py
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
      # nodeSelector:
      #   kops.k8s.io/instancegroup: load-test
