apiVersion: v1
kind: Service
metadata:
  name: locust
  labels:
    app: locust
spec:
  ports:
    - name: kube-znn
      targetPort: locust
      port: 8089
  selector:
    app: locust-master
  type: LoadBalancer